packages: []

minimumReleaseAge: 0

allowBuilds:
  esbuild: false
  sharp: false
  simple-git-hooks: false
  unrs-resolver: false
  workerd: true

overrides:
  lightningcss: "-"
  postcss: "-"
  rolldown: 1.2.0

patchedDependencies:
  discord-interactions: patches/discord-interactions.patch

savePrefix: ""
shellEmulator: true
