packages: []

overrides:
  "@antfu/eslint-config>@eslint/markdown": "-"
  "@antfu/eslint-config>@stylistic/eslint-plugin": "-"
  "@antfu/eslint-config>eslint-plugin-jsonc": "-"
  "@antfu/eslint-config>eslint-plugin-toml": "-"
  "@antfu/eslint-config>eslint-plugin-vue": "-"
  "@antfu/eslint-config>eslint-processor-vue-blocks": "-"
  "@antfu/eslint-config>jsonc-eslint-parser": "-"
  "@antfu/eslint-config>toml-eslint-parser": "-"
  "@antfu/eslint-config>vitest": "-"
  esbuild: 0.25.5
  eslint-plugin-pnpm>jsonc-eslint-parser: "-"
  is-core-module: npm:@nolyfill/is-core-module@^1
  safe-buffer: npm:@nolyfill/safe-buffer@^1
  zod: 3.25.50

patchedDependencies:
  discord-interactions: patches/discord-interactions.patch

savePrefix: ""
shellEmulator: true
