// Generated by Wrangler on Sat Nov 19 2022 16:32:41 CET
interface Env extends Record<string, unknown> {
  META: KVNamespace
  API_BASE: "https://dota.haglund.dev"
  DISCORD_BOT_TOKEN: string
  DISCORD_CLIENT_ID: "999099490273337354"
  DISCORD_CLIENT_SECRET: string
  DISCORD_PUBLIC_KEY: "7df58ea4839882888b45f9b56936b0e5e2f6f49fe1d0e88d2637cb4e14ce849c"
  MATCHES: D1Database
}
