/* eslint-disable */
// Generated by Wrangler by running `wrangler types` (hash: 0606e38f3be7444728ff450dcb692a22)
// Runtime types generated with workerd@1.20260714.1 2026-03-01 no_nodejs_compat_v2
interface __BaseEnv_Env {
  META: KVNamespace
  API_BASE: string
  DISCORD_BOT_TOKEN: string
  DISCORD_CLIENT_ID: "999099490273337354"
  DISCORD_CLIENT_SECRET: string
  DISCORD_PUBLIC_KEY: "7df58ea4839882888b45f9b56936b0e5e2f6f49fe1d0e88d2637cb4e14ce849c"
  MATCHES: D1Database
}
declare namespace Cloudflare {
  interface GlobalProps {
    mainModule: typeof import("./dist/index")
  }
  interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
