/* eslint-disable @typescript-eslint/consistent-type-definitions */

// Generated by Wrangler on Sat Nov 19 2022 16:32:41 GMT+0100 (centraleuropeisk normaltid)
interface Env {
  CACHE: KVNamespace
  META: KVNamespace
  API_BASE: "https://dota-matches-api.beequeue.workers.dev"
  DISCORD_BOT_TOKEN: string
  DISCORD_CLIENT_ID: "999099490273337354"
  DISCORD_CLIENT_SECRET: string
  DISCORD_PUBLIC_KEY: "7df58ea4839882888b45f9b56936b0e5e2f6f49fe1d0e88d2637cb4e14ce849c"
  WEBHOOKS: R2Bucket
  __D1_BETA__MATCHES: D1Database
}
