name = "dota-matches-api"
account_id = "a2ae71949fd5eaebc354f81fb3b1deab"
compatibility_date = "2022-11-19"
usage_model = "bundled"

triggers = { crons = ["0 9 * * *"] }

[[r2_buckets]]
binding = "WEBHOOKS"
bucket_name = "dota-matches-webhooks"

[[kv_namespaces]]
binding = "CACHE"
id = "36fe05a650434c41943c782672f104b4"
[[kv_namespaces]]
binding = "META"
id = "d36a2a6f8e86435aaf85c18801d813c7"

[[d1_databases]]
binding = "__D1_BETA__MATCHES"
database_name = "dota-matches"
database_id = "db7df0f4-2468-4396-80b8-06a97c52f32a"

[miniflare]
kv_persist = true
r2_persist = true
d1_persist = true

[vars]
API_BASE = "https://dota-matches-api.beequeue.workers.dev"
DISCORD_CLIENT_ID = "999099490273337354"
DISCORD_PUBLIC_KEY = "7df58ea4839882888b45f9b56936b0e5e2f6f49fe1d0e88d2637cb4e14ce849c"

[build]
command = "pnpm --silent build"
# The directory to watch for changes while using `wrangler dev`, defaults to the current working directory
watch_dir = "src"
[build.upload]
format = "modules"
main = "index.mjs"
