name = "dota-matches-api"
compatibility_date = "2022-07-17"
usage_model = "bundled"

kv_namespaces = [
  { binding = "CACHE", id = "36fe05a650434c41943c782672f104b4" }
]

[build]
command = "pnpm --silent build"
# The directory to watch for changes while using `wrangler dev`, defaults to the current working directory
watch_dir = "src"
[build.upload]
format = "modules"
main = "index.mjs"
