// @vitest-environment node
import { describe, expect, it } from "vitest"

import teamsPageFixture from "./fixtures/matches.html?raw"
import { parseMatchesPage } from "./parser.ts"

describe("parseMatchesPage", () => {
  /*
    Fixture is generated by this request:
    curl -X GET 'https://liquipedia.net/dota2/api.php' \
    --url-query 'action=parse' \
    --url-query 'format=json' \
    --url-query 'contentmodel=wikitext' \
    --url-query 'text={{#invoke:Lua|invoke|module=MatchTicker/Custom|fn=mainPage|dev=false|type=upcoming|limit=10|filterbuttons-liquipediatier=1,2|filterbuttons-liquipediatiertype=Monthly,Weekly,Qualifier,Misc,Showmatch,National,monthly,weekly,qualifier,misc,showmatch,national}}' \
    --header 'User-Agent: dota-matches-api-se' \
    --header 'Accept-Encoding: zstd,gzip'
  */
  it("correctly parses the body", async () => {
    const withoutHashes = await parseMatchesPage(teamsPageFixture)

    expect(withoutHashes).toMatchSnapshot()
  })
})
