name: e2e

on:
  workflow_dispatch:
    inputs:
      api_base:
        type: string
        default: https://dota.haglund.dev
        required: false
        description: The base URL of the API to test
  #schedule:
  #  - cron: "0 */4 * * *" # https://crontab.guru/#0_*/4_*_*_*

permissions:
  contents: read

concurrency:
  group: e2e
  cancel-in-progress: true

env:
  API_BASE: ${{ inputs.api_base || 'https://dota.haglund.dev' }}

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

      - uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
        with:
          node-version: 26

      - run: corepack enable

      - name: find pnpm cache path
        id: cache
        run: echo "path=$(pnpm store path)" >> $GITHUB_OUTPUT

      - uses: actions/cache@55cc8345863c7cc4c66a329aec7e433d2d1c52a9 # v6.1.0
        with:
          path: ${{ steps.cache.outputs.path }}
          key: v1-pnpm-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            v1-pnpm-

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - run: node --run test:e2e

      - name: ntfy_action
        uses: NiNiyas/ntfy-action@2fd8963f2092903578ac7303d30be47a675fc182 # v1.0.6
        if: ${{ failure() }}
        with:
          url: ${{ secrets.NTFY_URL }}
          topic: ${{ secrets.NTFY_TOPIC }}
          headers: ${{ secrets.NTFY_TOKEN }}
          title: dota-matches-api warning
          tags: warning
